Stewart onboard javascript
IMQS/onboard-javascript pull request #26
Opened 2017-05-04 11:52 UTC by stewartm83

Onboard solution can you review please.

2017-05-05 06:55 UTC, FritzOnFire commented
Haven't looked at the code yet, but the grid should fill the screen automatically, also when changing the window size we don't want to see a scroll bar, and if I hit the ">>" first the page does not update, and the text changes to "Page NaN of 100000", which is definitely not right.

2017-05-08 08:03 UTC, FritzOnFire commented
Please ignore your .js files with .gitignore

2017-05-08 08:31 UTC, FritzOnFire requested changes
You should have also used the JQuery that was included with the project, but I don't think that is such a big deal

2017-05-08 08:31 UTC, FritzOnFire commented on app.ts
> +		var header = document.createElement("thead");
don't use `var`

2017-05-08 08:31 UTC, FritzOnFire commented on app.ts
> +		var tableBody = document.createElement("tbody");
don't use `var`

2017-05-08 08:31 UTC, FritzOnFire commented on app.ts
> +				var tableRow = document.createElement("tr");
don't use `var`

2017-05-08 08:31 UTC, FritzOnFire commented on app.ts
> +					}</td><td>${val[9]}</td><td>${val[10]}</td>`;
I don't think this would work if you received more or less columns from the server.

2017-05-08 08:33 UTC, FritzOnFire commented
Also, the first time I click the `>` button, nothing happens

2017-05-08 11:46 UTC, FritzOnFire commented
I cant see the navigation buttons when the height of the window is small. And clicking the `>>` button after resizing creates a console error

2017-05-09 08:55 UTC, RoanBrand commented
This is hard to review with all the commits. Should he squash them before we give a review? @bmharper @dbferreira

2017-05-09 09:17 UTC, bmharper commented
I agree - can you squash your commits @stewartm83? If you've never squashed git commits, you'll probably want to go through some tutorial on doing it.

2017-07-03 20:33 UTC, closed without merging

2017-07-03 20:33 UTC, stewartm83 commented
Should it be closed?